[package]
name = "rsa"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-circuit-bigint = { path = "../..", default-features = false, features = ["unstable"] }
risc0-zkvm = { path = "../../../../zkvm", default-features = false, features = [
  "std", "unstable",
] }
risc0-zkvm-platform = { path = "../../../../zkvm/platform" }
num-bigint = { version = "0.4", default-features = false, features = ["serde"] }
