[package]
name = "cargo-risczero"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
description = "RISC Zero CLI tools"
readme = "README.md"
keywords = ["risc0", "risczero", "tool", "cli", "generate"]

[[bin]]
name = "r0vm"
doc = false

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
bincode = "1.3"
bonsai-sdk = { workspace = true }
bytemuck = "1.14"
cargo_metadata = { version = "0.18" }
clap = { version = "4.5", features = ["derive"] }
const_format = "0.2"
dirs = "5.0"
downloader = { version = "0.2", default-features = false, features = [
  "rustls-tls",
] }
flate2 = "1"
fs2 = "0.4"
fs_extra = "1.3.0"
hex = "0.4"
human-repr = { version = "1.0", features = ["1024"] }
regex = "1.10.6"
reqwest = { version = "0.11", default-features = false, features = [
  "json",
  "rustls-tls",
] }
reqwest-middleware = "0.2"
reqwest-retry = "0.4"
risc0-binfmt = { workspace = true, default-features = false }
risc0-build = { workspace = true }
risc0-r0vm = { workspace = true, optional = true }
risc0-zkvm = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "3.9"
syn = "2.0.72"
tabled = "0.15"
tar = "0.4"
tempfile = "3"
text_io = "0.1.12"
tokio = { version = "1", features = ["rt"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
xz = "0.1.0"
zip = { version = "2.1", optional = true }

[build-dependencies]
risc0-build = { workspace = true, optional = true }
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
], optional = true }
zip = { version = "2.1", optional = true }

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
# NOTE: cuda and metal are excluded because their build scripts require external tools.
features = ["docker", "r0vm"]

[features]
cuda = ["risc0-zkvm/cuda"]
default = ["r0vm"]
docker = []
experimental = [
  "dep:tracing-subscriber",
  "dep:risc0-build",
  "dep:zip",
  "risc0-zkvm/prove",
]
metal = []
r0vm = ["dep:risc0-r0vm"]
